version: '3.9'

services:
  nginx:
    image: nginx:1.24.0
    container_name: miam_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm
    container_name: miam_php
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql
    container_name: miam_mysql
    ports:
      - 8002:3306
    environment:
      MYSQL_DATABASE: miam
      MYSQL_USER: miamuser
      MYSQL_PASSWORD: miampassword
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - miam_db:/var/lib/mysql
volumes:
  miam_db: