version: '3.9'

services:
  nginx:
    image: nginx:1.24.0
    container_name: miam_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm
    container_name: miam_php
    volumes:
      - ./:/var/www/html